deployment_name: probe-idle
type: probe
purpose: other
target: null
capture_interface: eno2
probe_workflow: null
behavior_source: null
flavor_capacity:
  v1.14vcpu.28g: 1
deployments:
  - behavior: scripted-cpu
    flavor: v1.14vcpu.28g
    count: 1
