"""
Content generation prompts for LLM augmentation.
"""
from augmentations.content.prompts.default import (
    DEFAULT_PARAGRAPH_PROMPT,
    DEFAULT_SENTENCE_PROMPT,
    DEFAULT_WORD_PROMPT,
    DEFAULT_FILENAME_PROMPT,
    DEFAULT_SEARCH_PROMPT,
    DEFAULT_COMMENT_PROMPT,
    DEFAULT_HEADERS_PROMPT,
)
from augmentations.content.prompts.phase import (
    PHASE_PARAGRAPH_PROMPT,
    PHASE_SENTENCE_PROMPT,
    PHASE_SEARCH_PROMPT,
    PHASE_FILENAME_PROMPT,
    PHASE_COMMENT_PROMPT,
    TIME_OF_DAY_THEMES,
)

__all__ = [
    # Default prompts
    'DEFAULT_PARAGRAPH_PROMPT',
    'DEFAULT_SENTENCE_PROMPT',
    'DEFAULT_WORD_PROMPT',
    'DEFAULT_FILENAME_PROMPT',
    'DEFAULT_SEARCH_PROMPT',
    'DEFAULT_COMMENT_PROMPT',
    'DEFAULT_HEADERS_PROMPT',
    # PHASE prompts
    'PHASE_PARAGRAPH_PROMPT',
    'PHASE_SENTENCE_PROMPT',
    'PHASE_SEARCH_PROMPT',
    'PHASE_FILENAME_PROMPT',
    'PHASE_COMMENT_PROMPT',
    'TIME_OF_DAY_THEMES',
]
