"""
Mechanics prompts for agent behavior.
"""
from augmentations.mechanics.prompts.default import (
    DEFAULT_BROWSER_MECHANICS,
    DEFAULT_RESEARCH_MECHANICS,
    NO_MECHANICS,
)
from augmentations.mechanics.prompts.phase import (
    PHASE_BROWSER_MECHANICS,
    PHASE_RESEARCH_MECHANICS,
    MCHP_LIKE_BROWSER_MECHANICS,
    MCHP_LIKE_RESEARCH_MECHANICS,
    TIME_OF_DAY_MECHANICS,
)

__all__ = [
    # Default
    'DEFAULT_BROWSER_MECHANICS',
    'DEFAULT_RESEARCH_MECHANICS',
    'NO_MECHANICS',
    # PHASE
    'PHASE_BROWSER_MECHANICS',
    'PHASE_RESEARCH_MECHANICS',
    'MCHP_LIKE_BROWSER_MECHANICS',
    'MCHP_LIKE_RESEARCH_MECHANICS',
    'TIME_OF_DAY_MECHANICS',
]
